### ISSUE TITLE
Bug in `kinfitter.cc`

### ISSUE THREAD

**Issue by francescobrivio** [GilesStrong/cms_runII_data_proc#9]
There is a bug in `kinfitter.cc` in the case where only one of the two fits converge:
https://github.com/GilesStrong/cms_runII_data_proc/blob/7477b93f430dff6dc662b9ece50bcf437c55c586/processing/src/kinfitter.cc#L160-L163

this should be instead:
```
        else if (std::isnan(right_fit.second) || std::isnan(left_fit.second)) {
            if (std::isnan(right_fit.second)) { result = left_fit; }
            else { result = right_fit; }
        }
```
i.e. if `right_fit.second` is NaN then return `left_fit` (and _vice versa_).

**Comment by GilesStrong** [comment]
Thanks for spotting this @francescobrivio , I'll fix it and rerun everything.
